apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhooq-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jhooq-springboot
  template:
    metadata:
      labels:
        app: jhooq-springboot
    spec:
      containers:
        - name: springboot
          image: mani7444/jhooq-docker-demo:jhooq-docker-demo
          ports:
            - containerPort: 8866
          env:
            - name: PORT
              value: "8866"
---
apiVersion: v1
kind: Service
metadata:
  name: jhooq-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8866
  selector:
    app: jhooq-springboot
